### PR TITLE
migrate to null safety

### PR DESCRIPTION
**Pull request by tshedor**
Hey @jonsamwell I've been migrating some of my own packages to null safety and it's a real PITA but I'm getting the hang of it and thought I'd help you out if I could. This is a rough first pass and I'll be coming back to it; however, feel free to fork it, branch off of it, commit to it, whatever's easiest for you.

### CODE REVIEW

**Comment by pushpendraKh** [comment]
@tshedor any plan soon to complete this PR?

**Comment by Tiska** [comment]
@tshedor can we help you in this migration ?

**Comment by tshedor** [comment]
@pushpendraKh @Tiska Sorry, this is a side side effort for me (I've got packages of my own I'm still trying to migrate as their dependencies become null safe) and I haven't been as attentive as I should be.

I'd love the help. You can open [a PR against my branch](https://github.com/tshedor/dart_gherkin/tree/migrate-to-null-safety), and I'll merge in those changes so that this PR is updated. Does that work for everyone?

**Comment by tshedor** [comment]
@Tiska / @steadycoding I've finished this PR. It has all tests passing and was migrated by hand without the Dart migration tool (which may be a good or bad thing, to be seen).

**Comment by tshedor** [comment]
Ref #31 #32

**Comment by Tiska** [comment]
> @Tiska / @steadycoding I've finished this PR. It has all tests passing and was migrated by hand without the Dart migration tool (which may be a good or bad thing, to be seen).

Honestly I gave the tool a try but this package is too complex for auto migration, it cas eventually help, but null safety expose null problems that need small refacroring. I did not know enough about this package to migrate it so thanks a lot 🙂👍

**Comment by jonsamwell** [comment]
@tshedor @Tiska sorry for the lack of response here, I am back on this now and am aim to get this merged in and the null-safety release sorted next week.  Many many thanks for all your effort here!

**Comment by tshedor** [comment]
Resolving conflicts from #33

**Comment by jonsamwell** [comment]
@tshedor thanks for this, I decided to venture through this myself as it was a pretty massive change, your code as reference helped a lot, so many many thanks for spearheading this!

With that the current master branch has the null-safety migration as well as many changed needed for the `integration_test` package work in `flutter_gherkin`

**Pull request closed without merging**
