### PR TITLE
Simplify step()

### PR DESCRIPTION
**Pull request by comerc**
https://github.com/jonsamwell/flutter_gherkin/issues/95

### CODE REVIEW

**Comment by jonsamwell** [comment]
@comerc I don't think this is the solution to pattern problem you are having.  Steps should be immutable and allowing them to mutate the pattern would be bad

**Comment by jonsamwell** [comment]
What is the rationale for renaming `step` to `stepWhen`?

**Comment by comerc** [comment]
> @comerc I don't think this is the solution to pattern problem you are having. Steps should be immutable and allowing them to mutate the pattern would be bad

revert commit

**Comment by comerc** [comment]
> What is the rationale for renaming `step` to `stepWhen`?

https://github.com/jonsamwell/dart_gherkin/blob/9cc32b398ecdc774f266839039b0d6ebcea032c4/lib/src/gherkin/steps/step.dart#L73

**Comment by jonsamwell** [comment]
Sorry @comerc I am not sure I understand, please fully explain it's been a long day so it might take a while for me to caught up

**Comment by comerc** [comment]
I want to give the opportunity to use the new version of the function `step()` together with the old version - renamed to `stepWith()` to avoid name conflict.

Other solution - `step0()`? it's not beautiful ;)

**Comment by jonsamwell** [comment]
@comerc I am still not sure what the purpose of the PR is and what it enables / fixes?

**Pull request closed without merging**
