### PR TITLE
Scenario Context implementation

### PR DESCRIPTION
**Pull request by vrnvorona**
Small addition to World, allowing for data to be passed between test steps to avoid using globals and other nasty stuff.

### CODE REVIEW

**Comment by vrnvorona** [comment]
Tested this on integration_test version of flutter_gherkin (with modification since it is not yet flutter 2 there), but of course should be checked by you too.

**Comment by vrnvorona** [comment]
How I used it in my scenario:
Step to remember amount of cells with certain finder:
```
        final scenarioContext = context.world.scenarioContext;
        final cellVisibleAmount = OfficeScreen.officeCell.evaluate().length.toString();
        scenarioContext.setContext(OfficeParams.visibleOffices, cellVisibleAmount);
```
Step to compare after action:
```
        final scenarioContext = context.world.scenarioContext;
        final cellVisibleAmount = OfficeScreen.officeCell.evaluate().length;
        final cellAmountBefore = int.parse(scenarioContext.getContext(OfficeParams.visibleOffices));
        expect(cellVisibleAmount > cellAmountBefore, true);
```

**Comment by vrnvorona** [comment]
@jonsamwell not sure if you will get notified because I didn't add reviewers accidentally

**Comment by jonsamwell** [comment]
@vrnvorona could you give me an example of why you need to carry context between tests.  Strictly speaking tests should be atomic and not rely on a previous state another test has put the application in.  Therefore adding the ability to pass state information between tests goes against the principles of atomic testing.  However, I living in the real world it would be good to understand your scenario.

**Comment by vrnvorona** [comment]
@jonsamwell It's not carrying context between tests, between their steps. For example you need to remember how much items you have before editing cart and need to make "Then I have less items in cart". Maybe there is such mechanics already but I didn't find it.

Plus, scenarioContext is cleared after runScenario so, it's not carrying between tests.

**Comment by jonsamwell** [comment]
@vrnvorona sorry for the late reply here.  Unfortunately I don't think this is needed as this is exactly what the World object is for.  It allows you (once sub-classed) to store anything on and passed to all steps in a test. 

You can see rather naively in the example in this project there is a custom world that holds a variable that is passed between steps `https://github.com/jonsamwell/dart_gherkin/blob/master/example/supporting_files/worlds/custom_world.world.dart#L6`

However I am sure you can expand on that idea.

Please let me know if this does not met your needs

**Comment by vrnvorona** [comment]
@jonsamwell Looks good, though I am confused on how to use sub-classed World. Do I just change type of generic of step definition (when/then object) and it works? Sorry for lameness, haha

**Comment by jonsamwell** [comment]
@vrnvorona 

Not a problem you would do something like this

First create a custom world class

```
import 'package:example_with_integration_test/services/external_application_manager.dart';
import 'package:flutter_gherkin/flutter_gherkin.dart';

class CustomWorld extends FlutterWorld {
  void storeNumericInput(num val) {
    // store this
  }
}

```

Then assign the custom world to the world constructor in the configuration

```
import 'dart:async';
import 'package:gherkin/gherkin.dart';
import 'supporting_files/hooks/hook_example.dart';

Future<void> main() {
  final steps = [
  ];
  final config = TestConfiguration.DEFAULT(steps)
    ..createWorld =
        (TestConfiguration config) => Future.value(CustomWorld());

  return GherkinRunner().execute(config);
}

```

Then in a custom step you would do this:

```
import 'package:gherkin/gherkin.dart';
import '../worlds/custom_world.world.dart';

StepDefinitionGeneric GivenThePowersOfTwo() {
  return given2<num, num, CustomWorld>(
    'the powers {POW} and {POW}',
    (input1, input2, context) async {
      context.world.storeNumericInput(input1);
      context.world.storeNumericInput(input2);
    },
  );
}

```

**Pull request closed without merging**
